### PR TITLE
Fixed minor misleading comment

### PR DESCRIPTION
**Pull request by sarahmonod**
and changed the double quotes to single for consistency.

### CODE REVIEW

**Comment by sarahmonod** [comment]
This wiki page should also be updated: http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29

**Comment by dirk-thomas** [comment]
Thank you for paying attention to details!

**Comment by dirk-thomas** [comment]
Also cherry-picked to the _indigo-devel_ branch: 565a77f04f4fbc5fb49bca0b429cd15fbae3af46

**Comment by dirk-thomas** [comment]
The mentioned wiki page seems to not contains the buggy docblock though?

**Comment by sarahmonod** [comment]
Check out 1.2.1, The file contents look close to: then there are the same few mistakes.

**Comment by dirk-thomas** [comment]
The second code block in 1.2.1 looks like this for me?

```
  ...
  10     # In ROS, nodes are uniquely named. If two nodes with the same
  11     # node are launched, the previous one is kicked off. The
  12     # anonymous=True flag means that rospy will choose a unique
  13     # name for our 'listener' node so that multiple listeners can
  14     # run simultaneously.
  15     rospy.init_node('listener', anonymous=True)
  ...
```

**Comment by sarahmonod** [comment]
Weird. It was different for me yesterday, but now it seems fixed.

Although the quotes still seem inconsistent to me, I guess this is very minor and doesn't really require fixing :-P

**Comment by dirk-thomas** [comment]
If you see anything which needs to be updated please feel free to edit the wiki page.

**Pull request merged**
