### PR TITLE
Added galactic turtle icon.

### PR DESCRIPTION
**Pull request by kscottz**
Added the ROS 2 Galactic turtle icon.

### CODE REVIEW

**Comment by cottsay** [comment]
I believe that the new path needs to be added to list of turtles right here: https://github.com/ros/ros_tutorials/blob/74cc182dce2bb7d221052d1d45fe4ad0e7705843/turtlesim/src/turtle_frame.cpp#L77-L91

**Comment by kscottz** [comment]
Those are all ROS 1 but I  went and modified the ROS 2 distros.

**Comment by cottsay** [comment]
> Those are all ROS 1

Sorry about that - I had referenced the `noetic-devel` branch instead of `galactic-devel`.

> I went and modified the ROS 2 distros

Perfect, looks good.

**Comment by cottsay** [comment]
I pulled this change locally and it looks good!
TurtleSim

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14674/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9426/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12337/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14817/)

**Review by cottsay — APPROVED** [review]
Thanks!

**Pull request merged**
