### PR TITLE
Added CI Github action

### PR DESCRIPTION
**Pull request by ahcorde**

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
Do we actually need this?  We already have the Rpr jobs running on this repository, and I think it would be better to just stick with that (like we do for the rest of the core packages).  Is there a particular reason to add this one?

**Comment by ahcorde** [comment]
> Do we actually need this? We already have the Rpr jobs running on this repository, and I think it would be better to just stick with that (like we do for the rest of the core packages). Is there a particular reason to add this one?

The job is not active (for now), and this one is for free.

**Comment by clalancette** [comment]
> The job is not active (for now), and this one is for free.

It looks like it is active to me; at least, it seemed to run on this PR, and a couple of other ones that were recently opened.  You can see the list of times it ran in https://build.ros2.org/job/Rpr__ros_tutorials__ubuntu_noble_amd64/ .

Mostly I'm just trying to avoid having to maintain this in addition to the Rpr job, and to keep this repository acting like the rest of the core.

**Comment by ahcorde** [comment]
Sure, closing this then

**Pull request closed without merging**
