### PR TITLE
remove turtlesim velocity and use Twist msg

### PR DESCRIPTION
**Pull request by jihoonl**
Turtlesim with Twist message

### CODE REVIEW

**Comment by chadrockey** [comment]
Is geometry_msgs missing from the package.xml and CMakeLists?  Otherwise, each substitution looks good.  Will the tutorial pages need updated?

+1 to changing "turtle1/command_velocity", etc to "turtle1/cmd_vel"

Does everyone think that allowing the 'Pose' message to continue is fine?  Otherwise, we would have to introduce quaternion logic at this point... and pull in tf to do getYawFromQuaternion and getQuaternionFromYaw, etc.

**Comment by jihoonl** [comment]
I was unsure whether I should use geometry_msgs/Pose. Because Turtlesim/pose was providing both positions and velocity.

**Comment by chadrockey** [comment]
The standard for Pose + Velocities is nav_msgs/Odometry:
http://www.ros.org/doc/api/nav_msgs/html/msg/Odometry.html

However, like I said, orientation is given as a quaternion, so I'm not sure if it's worth including in the tutorials.  On the other hand, users have to get used to quaternions eventually.  :)

**Comment by dirk-thomas** [comment]
How is odometry related to that?

**Comment by chadrockey** [comment]
It's the most standard message we have for a robot reporting its position, orientation, linear velocities, and angular velocities.  The turtlesim/Pose message is a simplified nav_msgs/Odometry.

**Comment by jihoonl** [comment]
@dirk-thomas Both Odometry and turtlesim/Pose are providing position and velocity. 
@chadrockey I think it is better to leave turtlesim/Pose as it is. Since turtlesim is for very newbies, Odometry may introduce another difficulty to them. So I think it would be better to keep turtlesim simple but lead to next level. I think Odometry can be introduced in the intermediate level tutorial.

**Comment by dirk-thomas** [comment]
This issue is about the velocity message and topic name. Not about the pose and we should keep it that way.

**Comment by dirk-thomas** [comment]
Code changes look fine. But turtlesim does not depend on package which provides the Twist msg.

**Comment by jihoonl** [comment]
package.xml and Cmakelist updated. I wonder why it was compiling without this dependency though.

**Comment by jihoonl** [comment]
it was not alphabetic order...

**Pull request merged**
