### PR TITLE
Added common tests

### PR DESCRIPTION
**Pull request by ahcorde**
Added common tests and applied required changes

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Comment by ahcorde** [comment]
compiled up-to `turtlesim`  and test `turtlesim`.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18809/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13342/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19552/)

**Review by clalancette — COMMENTED** [review]
I have a question: since we are moving headers around, are there any downstream packages that depend on this package and will break?  I don't know if that is the case, but I think it is worthwhile checking before we potentially break them.  It's enough to just check on the packages released into Rolling; if there are no users there, then we are safe to do this.

**Comment by ahcorde** [comment]
@clalancette These headers are not `ament_export_include_directories` and I already checked and there is no packages using them. I would say we are safe

**Comment by clalancette** [comment]
> @clalancette These headers are not `ament_export_include_directories` and I already checked and there is no packages using them. I would say we are safe

All right, sounds good!

**Review by clalancette — APPROVED** [review]

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18835/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13363/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19580/)

**Comment by ahcorde** [comment]
Relaunched Windows, it was a failure fetching Qt

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19589/)

**Pull request merged**
