### PR TITLE
added pointcoud2 example

### PR DESCRIPTION
**Pull request by flynneva**

### CODE REVIEW

**Comment by flynneva** [comment]
should've done this awhile ago but this is a pr copying over the test I added for rviz: https://github.com/ros-visualization/rviz/pull/1514

**Comment by flynneva** [comment]
@clalancette any way we could merge this example?

**Comment by clalancette** [comment]
Pinging @sloretz and @mabelzhang as the maintainers

**Comment by flynneva** [comment]
friendly ping @sloretz and @mabelzhang

**Review by clalancette — APPROVED** [review]

**Pull request merged**
