### PR TITLE
adding png, svg, and source file for lunar tuturtle icon

### PR DESCRIPTION
**Pull request by wjwwood**
@mikaelarguedas

### CODE REVIEW

**Comment by wjwwood** [comment]
These are just the icons. The tutorial code needs to be updated use it I think.

**Comment by wjwwood** [comment]
I addressed that in 92eafb0 based on https://github.com/ros/ros_tutorials/commit/b7a78dbd569185618384878d73f1f8b2cccbb4fd

**Comment by dirk-thomas** [comment]
Please only add a single `png` or `svg` (the one used in the code). The art work and additional formats should go into the https://github.com/ros-infrastructure/artwork repo.

**Comment by wjwwood** [comment]
> Please only add a single png or svg (the one used in the code). The art work and additional formats should go into the https://github.com/ros-infrastructure/artwork repo.

I'm was just following the examples of indigo and kinetic, which both have svg and png. I just assumed the others didn't have the one or the other because who ever made them didn't think to include both. Also, the artwork repository doesn't yet contain any turtlesim icons or source files. I'd prefer to keep the files as-is.

**Comment by dirk-thomas** [comment]
If you think adding two file formats like for the other distros (where one of them is always unused) then sure we can keep both. But `lunar.afdesign` should certainly not be in this repo but in the artwork repo.

**Comment by wjwwood** [comment]
> But `lunar.afdesign` should certainly not be in this repo but in the artwork repo.

I would prefer to keep the source close to the image. Plus there is original source for the first turtle in `turtle.xar` (in this folder), but there are no turtlesim icons or sources in artwork. I would be more concerned if the source file was large, but it's only 74k, not much more than twice the size of the `svg`. I could compress it if that is the worry.

**Comment by wjwwood** [comment]
Actually it is already compressed, so compressing it made it bigger 😢.

**Comment by dirk-thomas** [comment]
Thanks for creating the Lunar icon - this is how it looks together with the existing ones:

all-turtles

I have cherry-picked the png, svg, and code change in b6c985fc77882cc4c2dc92560cb14819dee0ad78 and released a new lunar package version 0.8.0. I committed the afdesign file to the artwork repo: https://github.com/ros-infrastructure/artwork/commit/aeffa47272ee02c1623750e700d44e2c975efd04

**Pull request closed without merging**
