### PR TITLE
Update goal response callback signature

### PR DESCRIPTION
**Pull request by jacobperron**
The signature changed in https://github.com/ros2/rclcpp/pull/1311

Also remove related dead code.

Since this is not compatible with Foxy, I've created and targeted a new `galactic-devel` branch.

TODO:

- [x] Update ros2 repos file (https://github.com/ros2/ros2/pull/1034)
- [x] Update rosdistro for Rolling (https://github.com/ros/rosdistro/pull/26613)
- [x] Update release track for Rolling (https://github.com/ros2-gbp/ros_tutorials-release/pull/1)

### CODE REVIEW

**Comment by jacobperron** [comment]
CI: https://github.com/ros2/rclcpp/pull/1311#issuecomment-693702052

**Comment by dirk-thomas** [comment]
Please also update the branch in the gbp repository.

**Comment by jacobperron** [comment]
Done: https://github.com/ros2-gbp/ros_tutorials-release/pull/1

**Review by dirk-thomas — APPROVED** [review]
:+1: once PR CI is setup, ran and passed.

**Review by ivanpauno — APPROVED** [review]

**Pull request merged**
