### PR TITLE
Add noetic turtle

### PR DESCRIPTION
**Pull request by sloretz**
Add the Noetic turtle icon created by @ColeOSRF

Previous Melodic PR: #41

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please add a screenshot of the rendered turtlesim window with this turtle so see how it looks in the default background. All turtles can be shown by enabling this code block: https://github.com/ros/ros_tutorials/blob/cd4ed467c7bc4b86512fed1f82346b95bf313a31/turtlesim/src/turtle_frame.cpp#L115-L116

**Comment by sloretz** [comment]
> Please add a screenshot

Here it is:

Screenshot from 2020-05-05 16-41-50

**Comment by dirk-thomas** [comment]
Is the bottom part with the "N" intended to be as is? Just asking since I thought it looks awkward.

**Comment by sloretz** [comment]
> Is the bottom part with the "N" intended to be as is? Just asking since I thought it looks awkward.

Yup, PM'd to avoid spoiling the Noetic logo before it's announced

**Comment by ColeOSRF** [comment]
Easy to remove if need be. Just let me know.

**Review by dirk-thomas — APPROVED** [review]
I was just checking since it looked weird to me. If it is intentional it is fine as is.

**Pull request merged**
