### PR TITLE
Updated the coordinate system in /spawn service for consistency

### PR DESCRIPTION
**Pull request by jarvisschultz**
Simple fix to address #24.

### CODE REVIEW

**Comment by tfoote** [comment]
+1 thanks for the attention to detail. Do you know of anywhere in the tutorials which tell you want to set this value to in pixels?

**Comment by jarvisschultz** [comment]
The only places I know of where the `/spawn` service is mentioned is on the [Services section of the main turtlesim page](http://wiki.ros.org/turtlesim#Services), and the part about using `rosservice call` in the [Understanding ROS Services and Parameters tutorial](http://wiki.ros.org/ROS/Tutorials/UnderstandingServicesParams#rosservice_call). 

It does not mention that these are pixel coordinates in either of these places. Although the screenshots in the tutorial ([example](http://wiki.ros.org/ROS/Tutorials/UnderstandingServicesParams?action=AttachFile&do=get&target=turtle%28service%29.png)) implicitly show this because you are asked to spawn a turtle at (2,2,0), and it shows up in the upper left instead of the lower left.

**Comment by dirk-thomas** [comment]
I have merged your patch (with spaces around the operator) to the jade-devel (1f8dc05c9ee005e6b33da7ab8c61444a8270b6d5) as well as indigo-devel (08bf066356527198733444d92107ac317a36a2b0) branches.

**Comment by vale1904** [comment]
Sorry I didn't urderstand how to spawn correctly my turtles...I mean...How can I update the spawn service? thanks a lot

**Comment by dirk-thomas** [comment]
@vale1904 This ticket has been closed three years ago. I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Pull request closed without merging**
